const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,ROOT=__dirname,DATA=path.join(ROOT,'data.json'),sessions=new Map();
const files={'/':'public/index.html','/style.css':'public/style.css','/app.js':'public/app.js','/upgrade.css':'public/upgrade.css','/upgrade.js':'public/upgrade.js'};
const seed=()=>({users:[],teams:[{id:'product',name:'Product Studio',icon:'PS'},{id:'engineers',name:'Platform Engineering',icon:'PE'},{id:'design',name:'Design Systems',icon:'DS'}],messages:[{id:1,team:'product',author:'Alex Morgan',text:'The onboarding experiment is ready for review. We need a decision on the activation metric.',at:'09:24',global:true},{id:2,team:'engineers',author:'Mina Chen',text:'FYI: the service now uses idempotency keys to prevent duplicate mutations during retries.',at:'09:31',global:true},{id:3,team:'design',author:'Jon Bell',text:'Published the new component tokens and migration guide for everyone.',at:'09:42',global:true}],tasks:[{id:1,title:'Finalize Q3 onboarding flow',team:'product',owner:'Alex Morgan',due:'Aug 28',status:'In progress',assignee:'AM'},{id:2,title:'Implement event idempotency',team:'engineers',owner:'Mina Chen',due:'Aug 26',status:'Review',assignee:'MC'},{id:3,title:'Ship component token guide',team:'design',owner:'Jon Bell',due:'Aug 25',status:'Done',assignee:'JB'}],changes:[{id:1,hash:'a21e8f',title:'feat: add retry-safe payment mutations',author:'Mina Chen',file:'services/payments/mutations.ts',time:'12 min ago',kind:'Modified'},{id:2,hash:'e94c33',title:'docs: publish component token migration',author:'Jon Bell',file:'docs/design/tokens.md',time:'1 hr ago',kind:'Added'}]});
const data=()=>{if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(seed(),null,2));return JSON.parse(fs.readFileSync(DATA,'utf8'))};const save=d=>fs.writeFileSync(DATA,JSON.stringify(d,null,2));
const json=(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(body))};
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}));
const getBody=req=>new Promise((ok,bad)=>{let raw='';req.on('data',x=>raw+=x);req.on('end',()=>{try{ok(raw?JSON.parse(raw):{})}catch{bad(Error('Invalid request'))}})});
const safe=u=>({id:u.id,name:u.name,email:u.email,team:u.team}),hash=(p,s=crypto.randomBytes(16).toString('hex'))=>({salt:s,hash:crypto.scryptSync(p,s,64).toString('hex')});
const auth=(req,res)=>{const u=sessions.get(cookies(req).sid);if(!u)json(res,401,{error:'Please sign in to continue.'});return u};
const fallback=t=>/idempotency/i.test(t)?'It means the action can safely be repeated: even if a request is retried, it will not create duplicate results (such as charging twice).':`In plain language: ${t.replace(/\b(FYI|published|experiment|activation metric)\b/gi,'').trim()}. The sender is sharing this update so other teams can coordinate.`;
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);try{if(req.method==='GET'&&files[url.pathname]){const file=path.join(ROOT,files[url.pathname]),type=file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':'text/html';res.writeHead(200,{'Content-Type':`${type}; charset=utf-8`});if(url.pathname==='/')return res.end(fs.readFileSync(file,'utf8').replace('</body>','<link rel="stylesheet" href="/upgrade.css"><style>[hidden]{display:none!important}</style><script>document.addEventListener("DOMContentLoaded",()=>{const m=document.getElementById("modal");m.addEventListener("click",e=>{if(e.target===m)m.hidden=true})})</script><script src="/upgrade.js"></script></body>'));return fs.createReadStream(file).pipe(res)}if(!url.pathname.startsWith('/api/'))return json(res,404,{error:'Not found'});const d=data();
if(req.method==='POST'&&url.pathname==='/api/auth/signup'){const b=await getBody(req);if(!b.name||!b.email||!b.password||!b.team)return json(res,400,{error:'Complete every field.'});if(d.users.some(u=>u.email===b.email.toLowerCase()))return json(res,409,{error:'That email is already registered.'});const p=hash(b.password),u={id:crypto.randomUUID(),name:b.name.trim(),email:b.email.toLowerCase(),team:b.team,salt:p.salt,password:p.hash};d.users.push(u);save(d);const sid=crypto.randomUUID();sessions.set(sid,safe(u));res.setHeader('Set-Cookie',`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);return json(res,201,{user:safe(u)})}
if(req.method==='POST'&&url.pathname==='/api/auth/signin'){const b=await getBody(req),u=d.users.find(x=>x.email===String(b.email).toLowerCase());if(!u||hash(b.password,u.salt).hash!==u.password)return json(res,401,{error:'Incorrect email or password.'});const sid=crypto.randomUUID();sessions.set(sid,safe(u));res.setHeader('Set-Cookie',`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);return json(res,200,{user:safe(u)})}
if(req.method==='POST'&&url.pathname==='/api/auth/signout'){sessions.delete(cookies(req).sid);res.setHeader('Set-Cookie','sid=; HttpOnly; Path=/; Max-Age=0');return json(res,200,{ok:true})}if(req.method==='GET'&&url.pathname==='/api/auth/me'){const u=auth(req,res);if(u)json(res,200,{user:u,teams:d.teams});return}const u=auth(req,res);if(!u)return;
if(req.method==='GET'&&url.pathname==='/api/dashboard')return json(res,200,{teams:d.teams,messages:d.messages,tasks:d.tasks,changes:d.changes});
if(req.method==='POST'&&url.pathname==='/api/messages'){const b=await getBody(req);if(!b.text?.trim())return json(res,400,{error:'Message cannot be empty.'});const m={id:Date.now(),team:b.team||u.team,author:u.name,text:b.text.trim(),at:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),global:b.global!==false};d.messages.push(m);save(d);return json(res,201,{message:m})}
if(req.method==='POST'&&url.pathname==='/api/tasks'){const b=await getBody(req);if(!b.title?.trim()||!b.due)return json(res,400,{error:'Task name and deadline are required.'});const t={id:Date.now(),title:b.title.trim(),team:b.team||u.team,owner:u.name,due:b.due,status:'Planned',assignee:u.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()};d.tasks.push(t);save(d);return json(res,201,{task:t})}
if(req.method==='POST'&&url.pathname==='/api/changes'){const b=await getBody(req);if(!b.title?.trim()||!b.file?.trim())return json(res,400,{error:'Change title and file are required.'});const c={id:Date.now(),hash:crypto.randomBytes(3).toString('hex'),title:b.title.trim(),file:b.file.trim(),kind:b.kind||'Modified',author:u.name,time:'Just now'};d.changes.unshift(c);save(d);return json(res,201,{change:c})}
if(req.method==='POST'&&url.pathname==='/api/explain'){const b=await getBody(req),t=String(b.text||'');if(!process.env.GEMINI_API_KEY)return json(res,200,{explanation:fallback(t),source:'Nexus local explainer'});const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`Explain this company chat message in plain, concise language for a teammate who may not know its jargon. Do not add facts: ${t}`}]}]})}),g=await r.json(),explanation=g.candidates?.[0]?.content?.parts?.[0]?.text;return json(res,200,{explanation:explanation||fallback(t),source:explanation?'Gemini AI':'Nexus local explainer'})}return json(res,404,{error:'Not found'})}catch(e){console.error(e);json(res,500,{error:'Something went wrong.'})}}).listen(PORT,()=>console.log(`Nexus is running at http://localhost:${PORT}`));
